name: Optimized CI/CD Pipeline for Node.js to AWS Lightsail

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: |
          npm run build || echo "No build step needed"
      
      - name: Run tests
        run: echo "Running tests..."

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: Add SSH Key for Lightsail
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/lightsail_key
          chmod 600 ~/.ssh/lightsail_key

      - name: Deploy to AWS Lightsail
        env:
          LIGHTSAIL_IP: "3.11.239.230"
        run: |
          echo "Starting deployment to AWS Lightsail..."

          # SSH into Lightsail instance to fix permissions for /var/www/html directory
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/lightsail_key ubuntu@$LIGHTSAIL_IP "
            sudo mkdir -p /var/www/html &&
            sudo chown -R ubuntu:ubuntu /var/www/html &&
            sudo chmod -R 755 /var/www/html
          "

          # Use rsync to transfer files, making sure to use sudo for write permissions
          rsync -avzO --no-perms --delete --exclude='.git' --exclude='node_modules' \
            -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/lightsail_key" . \
            ubuntu@$LIGHTSAIL_IP:/var/www/html

          # SSH into Lightsail instance to install dependencies, start the app, and configure Nginx
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/lightsail_key ubuntu@$LIGHTSAIL_IP "
            # Install Node.js and npm if not installed
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - &&
            sudo apt-get install -y nodejs &&
            sudo apt-get install -y npm &&

            # Check if 'temp-conf' exists and move it
            if [ -f /tmp/temp-conf ]; then
              sudo mv /tmp/temp-conf /etc/nginx/sites-available/kdnplusappbackend;
              sudo ln -sf /etc/nginx/sites-available/kdnplusappbackend /etc/nginx/sites-enabled/kdnplusappbackend;
            fi

            # Install Nginx if it's missing
            if ! command -v nginx &> /dev/null; then
              sudo apt-get install -y nginx;
            fi

            # Reload Nginx to apply the new configuration
            sudo nginx -s reload;

            # Install npm dependencies and start the app
            cd /var/www/html &&
            npm install &&
            pkill -f 'node index.ts' || true && # Stop any running instance
            npx ts-node index.ts > /dev/null 2>&1 & # Start the Node.js app in the background
          "

          echo "Deployment completed successfully!"

      - name: Cleanup
        run: rm -f ~/.ssh/lightsail_key
